theme = "catppuccin_mocha"

[editor]
line-number = "relative"
color-modes = true
middle-click-paste = false
cursorline = true

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-indent-retain = 999

[editor.indent-guides]
render = true
character = "┊"

[editor.smart-tab]
"supersede-menu" = true

[keys.normal.space]
"." = "file_picker_in_current_buffer_directory"
"t" = [":toggle-option lsp.display-inlay-hints"]

[keys.normal]
esc = "collapse_selection"
D = "kill_to_line_end" # Make this yank first?
C = ["extend_to_line_end", "change_selection"] 
C-c = "copy_selection_on_next_line"
"K" = "hover"
"C-r" = "redo"
"-" = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
