[[mgr.prepend_keymap]]
on = "-"
run = "leave"
desc = "Navigate up a directory"

[[mgr.prepend_keymap]]
on = "<esc>"
run = "quit"
desc = "Quit Yazi"

[[mgr.prepend_keymap]]
on   = "<enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "f"
run = "search --via fd"
desc = "Find files with `fd`"

[[mgr.prepend_keymap]]
on = "s"
run = "search --via rg"
desc = "Find files with `rg`"

[[mgr.prepend_keymap]]
on = "<S-f>"
run = "filter"
desc = "Filter files"
